[workspace]

members = [
    "chocopy-rs",
    "chocopy-rs-common",
    "chocopy-rs-std",
    "chocopy-rs-tester",
]

default-members = [
    "chocopy-rs",
    "chocopy-rs-common",
    "chocopy-rs-std"
]
